// src/app/dragon-data/page.tsx
export default function DragonDataPage() {
  const stories = [
    { title: "Genesis: The First Data Dragon", file: "genesis-of-dragons.md", description: "The origin story of how Data Dragons came to be" },
    { title: "The Query Realm: Where Data Dragons Dwell", file: "data-dragons-story.md", description: "Complete taxonomy and world-building" },
    { title: "The Ghost Drake Uprising", file: "ghost-drake-uprising.md", description: "When null values gain sentience" },
    { title: "The Merge Dragon Scene", file: "merge-dragon-scene.md", description: "Identity crisis in joined tables" },
    { title: "Select All Finale", file: "select-all-finale.md", description: "The ultimate query that unites all dragons" },
    { title: "Three Moments", file: "three-moments.md", description: "Pivotal scenes in the Data Dragon saga" },
    { title: "Dragon-Verse Scene", file: "dragon-verse-scene.md", description: "Poetic exploration of the data realm" },
  ];

  const frameworks = [
    { title: "Data Story Framework", file: "data-story-framework.md", description: "The Ledger of Lost Lands narrative structure" },
    { title: "Databases & Dragons Poem", file: "databases_and_dragons_poem.md", description: "Poetic exploration of data ethics" },
  ];

  const modules = [
    { title: "Data Quality Decay Module", file: "dragonmodules/data-quality-decay-module.md", description: "When data degrades and dragons awaken" },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-900 via-slate-900 to-emerald-900">
      {/* Back link */}
      <div className="absolute top-4 left-4 z-10">
        <a
          href="/"
          className="text-sm text-gray-300 hover:text-white underline"
        >
          ← Back to Portfolio
        </a>
      </div>

      {/* Hero Section */}
      <section className="relative py-20 px-4 overflow-hidden">
        <div className="absolute inset-0 opacity-10 bg-[url('/images/cosmic/grok/00e09f3f-a612-4214-915b-45b23c05c2f9.jpg')] bg-cover bg-center" />

        <div className="relative container mx-auto max-w-6xl text-center">
          <div className="text-8xl mb-6">🐉</div>
          <h1 className="text-6xl font-bold mb-6 bg-gradient-to-r from-emerald-400 via-purple-400 to-pink-400 bg-clip-text text-transparent">
            Dragon Data Course
          </h1>
          <p className="text-2xl text-gray-300 mb-8">
            Where Fantasy Meets Data Ethics
          </p>
          <p className="text-xl text-gray-400 max-w-3xl mx-auto mb-12 leading-relaxed">
            An immersive educational experience teaching responsible data management through
            epic narratives, mythical creatures, and interactive games. Learn how Data Dragons
            are born from the gap between human complexity and digital simplification.
          </p>
        </div>
      </section>

      {/* Main Content */}
      <div className="container mx-auto max-w-6xl px-4 pb-20">

        {/* Interactive Games Section */}
        <section className="mb-16">
          <div className="bg-gradient-to-r from-purple-800/50 to-pink-800/50 rounded-2xl p-8 border border-purple-500/30">
            <div className="flex items-center gap-4 mb-6">
              <span className="text-5xl">🎮</span>
              <div>
                <h2 className="text-3xl font-bold text-purple-300">GemGames Collection</h2>
                <p className="text-gray-400">107 AI-generated interactive experiences</p>
              </div>
            </div>
            <p className="text-gray-300 mb-6">
              Explore a gallery of interactive HTML5 games and visualizations generated by Gemini AI,
              including Data Dragon ID Kit, Protocol DRAGON Server Guardian, and more.
            </p>
            <a
              href="/dragon-data/GemGames/extracted/index.html"
              className="inline-block px-8 py-4 bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 rounded-lg font-semibold transition-colors text-white"
            >
              🕹️ Play Games & Explore Gallery
            </a>
          </div>
        </section>

        {/* Story Chapters */}
        <section className="mb-16">
          <h2 className="text-4xl font-bold mb-8 text-emerald-400 flex items-center gap-3">
            <span>📖</span>
            Story Chapters
          </h2>
          <div className="grid md:grid-cols-2 gap-6">
            {stories.map((story, idx) => (
              <div
                key={idx}
                className="bg-gray-800/50 rounded-xl p-6 border border-gray-700 hover:border-emerald-500 transition-all"
              >
                <h3 className="text-xl font-bold text-emerald-300 mb-2">{story.title}</h3>
                <p className="text-gray-400 text-sm mb-4">{story.description}</p>
                <a
                  href={`/dragon-data/${story.file}`}
                  target="_blank"
                  className="text-emerald-400 hover:text-emerald-300 text-sm font-semibold"
                >
                  Read Story →
                </a>
              </div>
            ))}
          </div>
        </section>

        {/* Frameworks & Theory */}
        <section className="mb-16">
          <h2 className="text-4xl font-bold mb-8 text-purple-400 flex items-center gap-3">
            <span>📚</span>
            Frameworks & Theory
          </h2>
          <div className="grid md:grid-cols-2 gap-6">
            {frameworks.map((fw, idx) => (
              <div
                key={idx}
                className="bg-gray-800/50 rounded-xl p-6 border border-gray-700 hover:border-purple-500 transition-all"
              >
                <h3 className="text-xl font-bold text-purple-300 mb-2">{fw.title}</h3>
                <p className="text-gray-400 text-sm mb-4">{fw.description}</p>
                <a
                  href={`/dragon-data/${fw.file}`}
                  target="_blank"
                  className="text-purple-400 hover:text-purple-300 text-sm font-semibold"
                >
                  Read More →
                </a>
              </div>
            ))}
          </div>
        </section>

        {/* Course Modules */}
        <section className="mb-16">
          <h2 className="text-4xl font-bold mb-8 text-pink-400 flex items-center gap-3">
            <span>🎓</span>
            Course Modules
          </h2>
          <div className="grid md:grid-cols-2 gap-6">
            {modules.map((module, idx) => (
              <div
                key={idx}
                className="bg-gray-800/50 rounded-xl p-6 border border-gray-700 hover:border-pink-500 transition-all"
              >
                <h3 className="text-xl font-bold text-pink-300 mb-2">{module.title}</h3>
                <p className="text-gray-400 text-sm mb-4">{module.description}</p>
                <a
                  href={`/dragon-data/${module.file}`}
                  target="_blank"
                  className="text-pink-400 hover:text-pink-300 text-sm font-semibold"
                >
                  Study Module →
                </a>
              </div>
            ))}
          </div>
        </section>

        {/* Resources */}
        <section className="mb-16">
          <h2 className="text-4xl font-bold mb-8 text-blue-400 flex items-center gap-3">
            <span>📦</span>
            Resources & Materials
          </h2>
          <div className="grid md:grid-cols-3 gap-6">
            <div className="bg-gray-800/50 rounded-xl p-6 border border-gray-700 hover:border-blue-500 transition-all">
              <h3 className="text-xl font-bold text-blue-300 mb-2">Visual Course</h3>
              <p className="text-gray-400 text-sm mb-4">Interactive visual presentation</p>
              <a
                href="/dragon-data/dd101.html"
                target="_blank"
                className="text-blue-400 hover:text-blue-300 text-sm font-semibold"
              >
                View Presentation →
              </a>
            </div>

            <div className="bg-gray-800/50 rounded-xl p-6 border border-gray-700 hover:border-blue-500 transition-all">
              <h3 className="text-xl font-bold text-blue-300 mb-2">PDF Materials</h3>
              <p className="text-gray-400 text-sm mb-4">Downloadable course materials</p>
              <div className="space-y-2">
                <a
                  href="/dragon-data/Data Dragon ID Kit.pdf"
                  target="_blank"
                  className="block text-blue-400 hover:text-blue-300 text-sm"
                >
                  📄 Data Dragon ID Kit
                </a>
              </div>
            </div>

            <div className="bg-gray-800/50 rounded-xl p-6 border border-gray-700 hover:border-blue-500 transition-all">
              <h3 className="text-xl font-bold text-blue-300 mb-2">Character Stories</h3>
              <p className="text-gray-400 text-sm mb-4">Meet the protagonists</p>
              <div className="space-y-2">
                <a
                  href="/dragon-data/chimwemwe.pdf"
                  target="_blank"
                  className="block text-blue-400 hover:text-blue-300 text-sm"
                >
                  📄 Chimwemwe
                </a>
                <a
                  href="/dragon-data/noela.pdf"
                  target="_blank"
                  className="block text-blue-400 hover:text-blue-300 text-sm"
                >
                  📄 Noela
                </a>
                <a
                  href="/dragon-data/Quitunda.pdf"
                  target="_blank"
                  className="block text-blue-400 hover:text-blue-300 text-sm"
                >
                  📄 Quitunda
                </a>
              </div>
            </div>
          </div>
        </section>

        {/* About Section */}
        <section className="bg-gradient-to-r from-gray-800/50 to-gray-700/50 rounded-2xl p-8 border border-gray-600">
          <h2 className="text-3xl font-bold mb-4 text-gray-200">About the Course</h2>
          <div className="text-gray-300 space-y-4">
            <p>
              The Dragon Data Course uses fantasy storytelling to teach critical concepts in data ethics,
              particularly around resettlement projects and development initiatives. Data Dragons represent
              the gap between human complexity and digital simplification—they are born when we try to
              compress infinite human stories into finite database fields.
            </p>
            <p>
              <strong className="text-emerald-400">Core Themes:</strong> Digital dehumanization,
              quantification of loss, systemic inequality, and the responsibility of data stewards to
              honor the humanity behind every data point.
            </p>
            <p>
              <strong className="text-purple-400">Educational Approach:</strong> Through character-driven
              narratives, mythical creatures, interactive games, and practical modules, learners explore
              real-world data challenges in infrastructure projects while maintaining engagement through
              fantasy elements.
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}
